Description: Jerry Jones-Udacity-Server Deployment for Udagram Services

Parameters:
  EnvironmentName:
   Description: An Environment name that will be prefixed to Udagram resources.
   Type: String
   Default: UdacityProject-01

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to our Load Balancer
      GroupName: LoadBalancer
      VpcId:
        Fn::ImportValue: 
          !Sub "${EnvironmentName-VPCID}"
      SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to our host and limit SSH
      GroupName: WebServer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName-VPCID}"
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0 
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0 
      SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      
      
   